### ISSUE TITLE
Go is not reinstalled when the required version differs from the installed version

### ISSUE THREAD

**Issue by OrBin** [geerlingguy/ansible-role-go#1]
In [this section](https://github.com/geerlingguy/ansible-role-go/blob/master/tasks/main.yml#L2-L6), ansible checks if go is installed, then use this to avoid reinstalling if Go is already installed.
It runs `go version`, so it would be nice if it compared the output with the `go_version` role variable, to reinstall Go if the installed version is not the required one.

**Comment by OrBin** [comment]
> This issue has been marked 'stale' due to lack of recent activity. If there is no further activity, the issue will be closed in another 30 days. Thank you for your contribution!
> 
> Please read [this blog post](https://www.jeffgeerling.com/blog/2020/enabling-stale-issue-bot-on-my-github-repositories) to see the reasons why I mark issues as stale.

Waiting for a response [here](https://github.com/geerlingguy/ansible-role-go/pull/2#issuecomment-1294675729), since there's already a PR resolving this.

**Comment by geerlingguy** [comment]
Definitely not stale, thanks for pinging me on it! I've merged it and released 1.1.0.
